const char * html = "<!DOCTYPE html><html>"
"<head>"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"

"<link rel=\"icon\" href=\"data:,\">"

"<style>"

"html {"
" font-family: Helvetica;"
" display: inline-block;"
" margin: 0px auto;"
" text-align: center;"
"}"

"body {"
" background-color: #000000;"
"}"

"h1 {"
" color: #AAAAAA;"
"}"

"h2 {"
" color: #CCCCCC;"
" font-size:16px;"
"}"

".button-on {"
" background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #44c767), color-stop(1, #5cbf2a));"
" background:-moz-linear-gradient(top, #44c767 5%, #5cbf2a 100%);"
" background:-webkit-linear-gradient(top, #44c767 5%, #5cbf2a 100%);"
" background:-o-linear-gradient(top, #44c767 5%, #5cbf2a 100%);"
" background:-ms-linear-gradient(top, #44c767 5%, #5cbf2a 100%);"
" background:linear-gradient(to bottom, #44c767 5%, #5cbf2a 100%);"
" filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#44c767', endColorstr='#5cbf2a',GradientType=0);"
" background-color:#44c767;"
" -moz-border-radius:28px;"
" -webkit-border-radius:28px;"
" border-radius:28px;"
" border:1px solid #18ab29;"
" display:inline-block;"
" cursor:pointer;"
" color:#ffffff;"
" font-family:Arial;"
" font-size:16px;"
" padding:18px 50px;"
" text-decoration:none;"
" text-shadow:0px 1px 0px #2f6627;"
"}"

".button-off {"
" background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #fc8d83), color-stop(1, #fc8d83));"
" background:-moz-linear-gradient(top, #fc8d83 5%, #fc8d83 100%);"
" background:-webkit-linear-gradient(top, #fc8d83 5%, #fc8d83 100%);"
" background:-o-linear-gradient(top, #fc8d83 5%, #fc8d83 100%);"
" background:-ms-linear-gradient(top, #fc8d83 5%, #fc8d83 100%);"
" background:linear-gradient(to bottom, #fc8d83 5%, #fc8d83 100%);"
" filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fc8d83', endColorstr='#fc8d83',GradientType=0);"
" background-color:#fc8d83;"
" -moz-border-radius:28px;"
" -webkit-border-radius:28px;"
" border-radius:28px;"
" border:1px solid #d83526;"
" display:inline-block;"
" cursor:pointer;"
" color:#ffffff;"
" font-family:Arial;"
" font-size:16px;"
" padding:18px 50px;"
" text-decoration:none;"
" text-shadow:0px 1px 0px #b23e35;"
"}"

".button-ap {"
" -moz-box-shadow:inset 0px 1px 3px 0px #91b8b3;"
" -webkit-box-shadow:inset 0px 1px 3px 0px #91b8b3;"
" box-shadow:inset 0px 1px 3px 0px #91b8b3;"
" background-color:#768d87;"
" -moz-border-radius:5px;"
" -webkit-border-radius:5px;"
" border-radius:5px;"
" border:1px solid #566963;"
" display:inline-block;"
" cursor:pointer;"
" color:#ffffff;"
" font-family:Arial;"
" font-size:8px;"
" font-weight:bold;"
" padding:10px 20px;"
" text-decoration:none;"
" text-shadow:0px -1px 0px #2b665e;"
"}"

".button-station {"
" -moz-box-shadow:inset 0px 1px 0px 0px #ffffff;"
" -webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;"
" box-shadow:inset 0px 1px 0px 0px #ffffff;"
" background-color:#f9f9f9;"
" -moz-border-radius:6px;"
" -webkit-border-radius:6px;"
" border-radius:6px;"
" border:1px solid #dcdcdc;"
" display:inline-block;"
" cursor:pointer;"
" color:#666666;"
" font-family:Arial;"
" font-size:8px;"
" font-weight:bold;"
" padding:10px 20px;"
" text-decoration:none;"
" text-shadow:0px 1px 0px #ffffff;"
"}"

".button-fw {"
" -moz-box-shadow:inset 0px 0px 14px -3px #f2fadc;"
" -webkit-box-shadow:inset 0px 0px 14px -3px #f2fadc;"
" box-shadow:inset 0px 0px 14px -3px #f2fadc;"
" background-color:#dbe6c4;"
" -moz-border-radius:6px;"
" -webkit-border-radius:6px;"
" border-radius:6px;"
" border:1px solid #b2b8ad;"
" display:inline-block;"
" cursor:pointer;"
" color:#757d6f;"
" font-family:Arial;"
" font-size:8px;"
" font-weight:bold;"
" padding:10px 20px;"
" text-decoration:none;"
" text-shadow:0px 1px 0px #ced9bf;"
"}"

"</style>"

"<script type=\"text/javascript\">"
"/* iOS re-orientation fix */"
"if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i)) {"
"    /* iOS hides Safari address bar */"
"    window.addEventListener(\"load\",function() {"
"        setTimeout(function() {"
"            window.scrollTo(0, 1);"
"        }, 1000);"
"    });"
"}"
"</script>"

"</head>"
"<body><h1>Camper Control</h1>"

"%BUTTON_1%"
"%BUTTON_2%"
"%BUTTON_3%"
"%BUTTON_4%"
"<p>%MODE% %UPDATE%</p>"
"%TEMPERATURE%"
"%CURRENT%"

"</body></html>";
